server:
  port: 8080
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/515_project
    username: root
    password: 940558
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.gnibbuq.pojo
  mapper-locations: /mybatis/mapper/*.xml
